### ISSUE TITLE
Bug - Administration Settings

### ISSUE THREAD

**Issue by barnabashohl** [OliverParoczai/nextcloud-unroundedcorners#20]
When I visit the _Administration Settings_, the last bullet in the main navigation is nearly hidden.

![grafik](https://user-images.githubusercontent.com/20787965/203965733-93c77312-2a16-417d-ac2b-b594e39172b4.png)

Quick and Dirty fix:
`#app-navigation:not(.vue) { 
    height: calc(100% - 50px); 
}`

Nextcloud Hub 3 (25.0.1)
Firefox (107.0)

**Comment by OliverParoczai** [comment]
Hello!

Thanks for sending the issue. This problem was one that I also experienced while debugging one time, but couldn't reproduce.
Hardcoding -50px doesn't work since on most devices it adds a blank bar, since most of the time it's sized correctly. I think this could be attributed to some kind of calculation error that doesn't work with 0.

Could you try replacing the following
```
:root { /* Body container settings */
--body-container-margin: 0px !important;
--body-container-radius: 0px !important;
}
```
with:
```
:root { /* Body container settings */
--body-container-margin: 0.01px !important;
--body-container-radius: 0.01px !important;
}
```
and reporting if anything changes?

Thanks,
Oliver

**Comment by barnabashohl** [comment]
Sorry for my late reply. I am not that active at GitHub.

I had to reinstall Nextcloud because I completely broke my NC25 test instance. And now I can't reproduce my problem too.
Everything works as it should.

The error only occurred in the administration settings, although the navigation is the same everywhere. So that was kind of weird.
If I can reproduce the error again, I'll open a new ticket.

Thanks for your work!

**Comment by OliverParoczai** [comment]
No problem, thanks for your support and feedback!

Let me know if there is any other kind of problem, or if the problem reappears, I will be happy to help

Thank you,
Oliver
