### ISSUE TITLE
Round corners in the Files navigation

### ISSUE THREAD

**Issue by pbalthasar** [OliverParoczai/nextcloud-unroundedcorners#29]
I still found some round corners when viewing files and hovering over parent folders. Screenshot sadly doesn't show the mouse, but it's hovering the "all files" section. 

![Screenshot 2024-04-19 at 14 50 41](https://github.com/OliverParoczai/nextcloud-unroundedcorners/assets/16125838/ba6a31da-6845-42d8-8373-f530b0cb0082)

**Comment by OliverParoczai** [comment]
Hello! The patch will be out by tomorrow.

I have already sent the fix into the repo about a month ago via 39c45b2aaaf9b78f2cdc7caf5967e16e3519aa1b, but it got delayed from the release since I didn't have access to the computer that housed the release keys for the Nextcloud App Store.

Let me know if there are any other problems.

Thanks,
Oliver
