### ISSUE TITLE
Nextcloud mail reload button broken

### ISSUE THREAD

**Issue by dodedodo** [OliverParoczai/nextcloud-unroundedcorners#8]
Hello!

With unrounded corners active, the appearance of the nextcloud mail reload button is broken. The button rotates while it's fetching mail, but with the rectangular outline this looks quite odd. 

It's not that clear on the image below, but it does catch the eye when it's actually moving on your screen.

![image](https://user-images.githubusercontent.com/3252036/146258348-4494d854-8e97-4142-b491-aa12d7fa3134.png)

**Comment by OliverParoczai** [comment]
Hello! Seems like the last patch overwrote some of the overrides that I have added manually, will look into this when I get home! Thanks for your support

**Comment by OliverParoczai** [comment]
Found the problem, it was caused by the specific overriding CSS being at the start of the file, and there was another override below it that caused all buttons to get the new default values, and that also applied the override to our specific one.
I will be pushing the new update out in a few minutes, it should be available in the updater in 2-3 hours.

Thank you again for your feedback!
